### ISSUE TITLE
Can you make the script select Darker color

### ISSUE THREAD

**Issue by prnv44** [metafates/ChromiumPywal#1]
https://github.com/adi1090x/polybar-themes/blob/master/bitmap/material/scripts/pywal.sh  or pywalfox for reference

**Comment by metafates** [comment]
I don't think I will. But you can make a fork and change it with ease. Colors are defined [here](https://github.com/metafates/ChromiumPywal/blob/9d7c5847b221d2ff39b3bd5082741759cc6b6453/generate-theme.sh#L34)
